Peppermint
0xPolygon/tendermint pull request #1
Opened 2018-10-20 16:37 UTC by vaibhavchellani

* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG_PENDING.md

2018-10-20 17:39 UTC, jdkanani requested changes

2018-10-20 17:39 UTC, jdkanani commented on config/config.go
> +		CreateEmptyBlocksInterval:   5000,
Let's increase to somewhere 120 * 60 !?

2018-10-20 17:39 UTC, jdkanani commented on consensus/state.go
> +	cs.Logger.Info("[STATE] app hash", "apphash", hex.EncodeToString(cs.state.AppHash), "lastBlockMeta", hex.EncodeToString(lastBlockMeta.Header.AppHash))
Do we need this log?

2018-10-20 17:39 UTC, jdkanani commented on consensus/state.go
> +	cs.Logger.Info(fmt.Sprintf("%v", block))
Needed?

2018-10-20 17:39 UTC, jdkanani commented on consensus/state.go
> +		cs.Logger.Info("[peppermint] sign add vote", "lockedHeaderHash", hex.EncodeToString(header.Hash), "lockedBlockDataHash", hex.EncodeToString(cs.LockedBlock.DataHash))
Do we need this log?

2018-10-20 17:39 UTC, jdkanani commented on consensus/state.go
> +	cs.Logger.Info("[peppermint] vote sign with data", "signBytes", vote.SignBytes(cs.state.ChainID))
Change this to debug.

2018-10-20 17:39 UTC, jdkanani commented on privval/priv_validator.go
> +
Do we need spaces? :)

2018-10-20 17:39 UTC, jdkanani commented on privval/priv_validator.go
> +		}else {
Lint please.

2018-10-20 17:39 UTC, jdkanani commented on rpc/core/mempool.go
> +	logger.Info("The transaction recieved is ",hex.EncodeToString(tx),"transaction")
Change it to Debug? and lint please.

2018-10-20 17:39 UTC, jdkanani commented on state/execution.go
> +	fmt.Errorf("abci resposnse %v",abciResponses)
Please remove

2018-10-20 17:39 UTC, jdkanani commented on state/execution.go
> +	fmt.Println("No error in getting validator updates , updates := %v",updates)
```suggestion
	fmt.Println("Validator updated successfully. Updates: %v",updates)
```

2018-10-20 17:39 UTC, jdkanani commented on types/block.go
> +	//todo maybe add votes here /maybe not
```suggestion
	// TODO maybe add votes here
```

2018-10-20 17:39 UTC, jdkanani commented on types/genesis.go
> +	fmt.Printf("here in validate and complete with gen doc as %v",genDoc.ConsensusParams)
Please remove

2018-10-20 17:39 UTC, jdkanani commented on types/genesis.go
> +	genDoc.ConsensusParams = DefaultConsensusParams()
What is this for?

2018-10-20 17:39 UTC, jdkanani commented on types/genesis.go
> +		fmt.Println("___> here")
Please remove

2018-10-20 17:39 UTC, jdkanani commented on types/params.go
> +		fmt.Println(params.BlockSize)
Please remove

2018-10-20 17:39 UTC, jdkanani commented on types/protobuf.go
> +	fmt.Errorf("****** the type observed is*********")
Please remove this `Errorf`

2018-10-20 17:39 UTC, jdkanani commented on types/protobuf.go
> +	sizeSecp := 65
May be add `// [peppermint]` !?

2018-10-20 17:39 UTC, jdkanani commented on types/tx.go
> +	fmt.Printf("********* Inside TM Hash with tx as %v and string ", tx)
please remove :)

2018-10-21 18:34 UTC, vaibhavchellani commented on types/genesis.go
> +	genDoc.ConsensusParams = DefaultConsensusParams()
setting the default consensus params

2018-10-21 18:38 UTC, vaibhavchellani commented on config/config.go
> +		CreateEmptyBlocksInterval:   5000,
done :)

2018-10-21 18:38 UTC, vaibhavchellani commented
Updates have been made .

2018-10-21 18:51 UTC, jdkanani requested changes

2018-10-21 18:51 UTC, jdkanani commented on privval/priv_validator.go
> +func (pv *FilePV) SignHello(chainID string, data string) ([]byte, error) {
Do we need this?

2018-10-21 18:51 UTC, jdkanani commented on types/genesis.go
> +	genDoc.ConsensusParams = DefaultConsensusParams()
```golang
if genDoc.ConsensusParams == nil {
    genDoc.ConsensusParams = DefaultConsensusParams()
} else {
	if err := genDoc.ConsensusParams.Validate(); err != nil {
	    return err
	}
}
```

no?

2018-10-21 18:54 UTC, jdkanani approved these changes

2018-10-21 18:55 UTC, merged