Added votes to header + added secp256k1 eth sigs
0xPolygon/tendermint pull request #6
Opened 2019-05-11 06:28 UTC by vaibhavchellani

2019-05-11 06:28 UTC, vaibhavchellani commented
@jdkanani Please review latest-commit

2019-05-16 06:21 UTC, jdkanani requested changes

2019-05-16 06:21 UTC, jdkanani commented on types/protobuf.go
> +	fmt.Printf("inside Protobuf.go %v", reqBodyBytes.String())
Remove unwanted prints

2019-05-16 06:21 UTC, jdkanani commented on types/protobuf.go
> +	//TODO check if this works as supposed to when multiple validators
Please check with multiple validators.

2019-05-16 06:21 UTC, jdkanani commented on types/canonical.go
> +	// TODO Make sure this works in contract
Please check and make sure before we go ahead

2019-06-01 10:50 UTC, jdkanani commented
@vaibhavchellani Any timeline for this?

2019-06-02 06:43 UTC, vaibhavchellani commented
Should be done in the next couple of days, undergoing testing with heimdall.

2019-06-02 07:28 UTC, jdkanani commented
Also test with root contracts and checkpoints.

2019-12-23 16:33 UTC, closed without merging